jenkinsci/p4-plugin

src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java, src/main/java/org/jenkinsci/plugins/p4/credentials/P4Credentials.java, src/main/java/org/jenkinsci/plugins/p4/workspace/Workspace.java
This issue cropped up when I was attempting to force sync in a workflow build. Example stacktrace included below.
org.jenkinsci.plugins.workflow.cps.steps.ParallelStepException: Parallel step product1 failed
at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:153)
at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:119)
at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:294)
at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
at com.cloudbees.groovy.cps.Next.step(Next.java:58)
at …
=> [JENKINS-28213] Force syncing a workspace that does not exist on the filesystem causes a FileNotFoundException

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/test/java/org/jenkinsci/plugins/p4/PerforceScmTest.java
Do not assume that the user has selected "Perforce: Matrix Options".
If user has selected "Classic" matrix execution strategy (the default)
the perforce plugin would previously have thrown a null pointer exception.
Instead, we should just proceed forward with the default behavior
=> Fix JENKINS-28726: Allow for default matrix execution strategy

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
Proposed fix for https://issues.jenkins-ci.org/browse/JENKINS-29818
=> Fixed issue with workflow-plugin when setting changelog to false

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
[JENKINS-29979](https://issues.jenkins-ci.org/browse/JENKINS-29979)
@reviewbybees
=> [JENKINS-29979]: Override isApplicable for Pipeline compatibility

src/main/java/org/jenkinsci/plugins/p4/trigger/P4Trigger.java, src/test/java/org/jenkinsci/plugins/p4/client/ConnectionTest.java
@reviewbybees Changes to make the P4 Trigger pipeline compatible. Added some tests of the P4 trigger for both Pipeline/Non Pipeline jobs.
=> Jenkins 25249

src/main/java/org/jenkinsci/plugins/p4/trigger/P4Hook.java, src/main/java/org/jenkinsci/plugins/p4/trigger/P4Trigger.java
Fixed issues introduced in https://github.com/jenkinsci/p4-plugin/pull/24
=> [JENKINS-25249]: Fixed Null Pointer dereference

src/main/java/org/jenkinsci/plugins/p4/workflow/P4Step.java
This change allows Manually defined workspaces to be used as the source of a 'p4sync' in a pipeline/workflow project.
=> Custom workspace support

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4.java, src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4Task.java, src/main/java/org/jenkinsci/plugins/p4/groovy/P4Groovy.java, src/main/java/org/jenkinsci/plugins/p4/groovy/P4GroovyTask.java
Addresses JENKINS-41498
P4 groovy commands were invoking p4java directly, resulting in the Perforce operations being executed on the master.
Tried to keep the implementation as minimal as possible by extending AbstractTask.
=> P4Groovy execution to run on the slave

src/main/java/org/jenkinsci/plugins/p4/tagging/TagAction.java, src/test/java/org/jenkinsci/plugins/p4/client/JenkinsfileTest.java
Fixes for the issue (https://issues.jenkins-ci.org/browse/JENKINS-43770).
=> [JENKINS-43770] p4sync in parallel causes invalid SCM triggering

src/main/java/org/jenkinsci/plugins/p4/tagging/TagAction.java
I propose a fix for the issue: JENKINS-43877.
=> JENKINS-43877: P4 plugin fails during polling for freestyle job

src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
Added missing revision specification to printFile.
=> Fix unshelving of exclusively checked out files

pom.xml, src/main/java/org/jenkinsci/plugins/p4/trigger/P4Trigger.java
add the option to activate "Perforce triggered build." in declarative pipeline jobs
=> add support for "P4Trigger" declarative pipeline trigger

src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/BranchesScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/GlobalLibraryScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/GraphScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/StreamsScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/SwarmScmSource.java, src/main/java/org/jenkinsci/plugins/p4/workspace/WorkspaceSpec.java, src/main/resources/org/jenkinsci/plugins/p4/scm/GlobalLibraryScmSource/config-detail.jelly, src/main/resources/org/jenkinsci/plugins/p4/scm/GlobalLibraryScmSource/help-path.html, src/test/java/org/jenkinsci/plugins/p4/client/WorkflowTest.java
=> Global Pipeline Library support.

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java, src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
- Added a null check in getSwarm
- Don't create a SwarmBrowser when getSwarm returns null
See https://issues.jenkins-ci.org/browse/JENKINS-47336.
=> Fix changelog issues caused by NullPointerException in getSwarm

src/main/java/org/jenkinsci/plugins/p4/NodeHelper.java, src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/tasks/AbstractTask.java
Standardize the evaluation of what NODE_NAME in p4 workspace name generation
=> Standardize the evaluation of what NODE_NAME in p4 workspace name generation

src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/BranchesScmSource.java, src/main/resources/org/jenkinsci/plugins/p4/scm/BranchesScmSource/config-detail.jelly, src/main/resources/org/jenkinsci/plugins/p4/scm/BranchesScmSource/help-mappings.html
Fixed pull request with unchanged files reverted.
Fixed default filter and mappings
=> Add the ability to provide a view spec to Helix Branches SCM

src/main/java/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl.java, src/main/resources/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl/config.jelly, src/main/resources/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl/help-patternList.html, src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
Adding some UI alerts when we detect bad entries (along with a new assert in the tests)
=> Adding UI alerts for Pattern Filter errors

src/main/java/org/jenkinsci/plugins/p4/scm/BranchesScmSource.java, src/test/java/org/jenkinsci/plugins/p4/DefaultEnvironment.java, src/test/java/org/jenkinsci/plugins/p4/client/JenkinsfileTest.java, src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java, src/test/java/org/jenkinsci/plugins/p4/client/WorkflowTest.java
Updated tests to work against Windows, and lower spec computers. Due to issues I had running the tests  with windows.
=> JENKINS-52145-Updated tests to work against Windows, and lower spec computers

src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
Unofficial support for BuildReplica by ignoring revert warning message. JENKINS-52088
=> Support ServerID on client for Edge type serves.

src/main/java/org/jenkinsci/plugins/p4/scm/GlobalLibraryScmSource.java
Hide Helix Library from Add Source option in MultiBranch
=> Hide Helix Library from Add Source option in MultiBranch

src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java, src/main/resources/org/jenkinsci/plugins/p4/scm/BranchesScmSource/help-filter.html
Made two changes: Added help text for Include and Fixed incorrect images
=> Jenkinsci master

docs/POSTBUILDPUBLISHASSETS.md, src/main/java/org/jenkinsci/plugins/p4/ConfigurationListener.java, src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java, src/main/java/org/jenkinsci/plugins/p4/publish/CommitImpl.java, src/main/java/org/jenkinsci/plugins/p4/publish/Publish.java, src/main/java/org/jenkinsci/plugins/p4/publish/ShelveImpl.java, src/main/java/org/jenkinsci/plugins/p4/publish/SubmitImpl.java, src/main/resources/org/jenkinsci/plugins/p4/publish/ShelveImpl/config.jelly, src/main/resources/org/jenkinsci/plugins/p4/publish/SubmitImpl/config.jelly, src/test/java/org/jenkinsci/plugins/p4/DefaultEnvironment.java, src/test/java/org/jenkinsci/plugins/p4/client/PublishTest.java, src/test/java/org/jenkinsci/plugins/p4/publish/PurgeLimitTest.java
Fix for https://issues.jenkins-ci.org/browse/JENKINS-56414
=> JENKINS-56414: Support of Reconcile with Modtime in P4Publish

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
Apologies for the multiple commits... tried to squash and just made it worse and I think you can squash when merging the pull request.
=> Lower print out for null changelog to logger.fine()

src/main/java/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor.java
JENKINS-60141: Refactored to reduce number of calls to login -s
=> JENKINS-60141: Refactored to reduce number of calls to login -s

src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java, src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java, src/main/java/org/jenkinsci/plugins/p4/scm/P4SCMProbe.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
Correctly detect jenkinsfiles in virtual streams by using client syntax.
=> Add virtual stream detection for MultiBranch pipeline.  JENKINS-62699

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
Fix for https://issues.jenkins-ci.org/browse/JENKINS-56248
=> JENKINS-56248: P4Plugin Polls Workspaces With Disabled Polling (poll: false)

src/main/java/org/jenkinsci/plugins/p4/workspace/ManualWorkspaceImpl.java
Support for storing the "Manual Spec" in a file in Perforce.
The content of the "View" field on the Jenkins config form is stored in a file in Perforce,
the name of the file is now stored in the "View" field, prefixed with an "@".
This adds missing functionality that is needed to migrate from the old Perforce plugin to the new P4 plugin
(now it's finally no longer working due to the tables-to-div changes)
=> Implemented support for "Manual Spec" stored in a file in Perforce

src/main/java/org/jenkinsci/plugins/p4/client/SessionHelper.java
=> If Credential ID exists in session cache, set the connection's Ticket

src/main/java/org/jenkinsci/plugins/p4/client/SessionHelper.java
Previously logging was at level info, producing copious
logging.
Also remove logging of ticket value.
Fix for JENKINS-68006
- [x ] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> User session cache logging level changed to finer/finest

pom.xml, src/main/java/org/jenkinsci/plugins/p4/scm/P4SCMFileSystem.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
=> Update Jenkins version to 2.138.4

src/main/java/org/jenkinsci/plugins/p4/tasks/UnshelveTask.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
changes (pipeline)
WHAT
==================================================
In UnshelveTask added step to save unshelve change
to the changelog file.
=> JENKINS-38781 : p4 unshelve not updating

pom.xml
=> Update P4Java Version to 2022.1.2350821

src/test/java/org/jenkinsci/plugins/p4/client/PublishTest.java
https://github.com/jenkinsci/p4-plugin/pull/160/
=> Added test case for PR.

src/main/java/org/jenkinsci/plugins/p4/client/ConnectionFactory.java, src/main/resources/org/jenkinsci/plugins/p4/credentials/P4PasswordImpl/help-trust.html, src/main/resources/org/jenkinsci/plugins/p4/credentials/P4TicketImpl/help-trust.html, src/test/java/org/jenkinsci/plugins/p4/SimpleTestServer.java, src/test/java/org/jenkinsci/plugins/p4/tagging/TaggingTest.java
https://github.com/jenkinsci/p4-plugin/pull/157
=> Added Test Case for PR:https://github.com/jenkinsci/p4-plugin/pull/157

pom.xml, src/main/java/org/jenkinsci/plugins/p4/trigger/P4Trigger.java, src/test/java/org/jenkinsci/plugins/p4/client/JenkinsfileTest.java, src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java, src/test/java/org/jenkinsci/plugins/p4/client/WorkflowTest.java, src/test/java/org/jenkinsci/plugins/p4/credentials/PerforceCredentialsTest.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
1. Upgrade jenkins version to 2.222.4
2. Update dependencies to the latest supported by jenkins version 2.222.4
3. Need to update few test because of the new dependencies versions
=> Security Patch : Update Jenkins Version and Other Dependencies 

src/main/java/org/jenkinsci/plugins/p4/workspace/TemplateWorkspaceImpl.java, src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
Fix for the bug:
https://issues.jenkins.io/browse/JENKINS-59300
Fixes to reduce Warning by Static Code Analysis
=> Polling should not set client root to Null.

RELEASE.md, pom.xml, src/test/java/org/jenkinsci/plugins/p4/client/FreeStyleTest.java, src/test/java/org/jenkinsci/plugins/p4/client/WorkflowTest.java, src/test/java/org/jenkinsci/plugins/p4/client/WorkspaceTest.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
=> Update Jenkins Version to 2.346.3

pom.xml
=> Update P4 Java Version to "2022.1.2423241"

Jenkinsfile-integ, pom.xml
=> Update p4Java version to: 2022.2.2444480

src/main/java/org/jenkinsci/plugins/p4/filters/FilterLatestWithPinImpl.java, src/main/java/org/jenkinsci/plugins/p4/tasks/PollTask.java, src/main/resources/org/jenkinsci/plugins/p4/filters/FilterLatestWithPinImpl/config.jelly, src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
pinned changelist and trigger the build.
This feature will get enabled by build filter
"Polling latest change with pin". If this
filter is false, then exiting behaviour.
https://issues.jenkins.io/browse/JENKINS-63879
```[tasklist]
```
=> Add new feature to detect change beyond

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/workflow/P4Step.java, src/main/java/org/jenkinsci/plugins/p4/workflow/source/StreamSource.java, src/main/java/org/jenkinsci/plugins/p4/workspace/StreamWorkspaceImpl.java, src/main/resources/org/jenkinsci/plugins/p4/workflow/source/StreamSource/config.jelly, src/main/resources/org/jenkinsci/plugins/p4/workspace/StreamWorkspaceImpl/config.jelly, src/test/java/org/jenkinsci/plugins/p4/client/StreamAtChangeTest.java
=> Add stream at change in StreamWorkspace and P4Sync

src/main/java/org/jenkinsci/plugins/p4/review/ApproveNotifier.java, src/main/java/org/jenkinsci/plugins/p4/review/ApproveState.java, src/main/java/org/jenkinsci/plugins/p4/scm/SwarmScmSource.java, src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmHelper.java, src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmProjectAPI.java, src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmQueryAction.java, src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmReviewAPI.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
=> Change Swarm API to v11

pom.xml
=> Use bom-2.361 for dependency management.

src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java, src/main/java/org/jenkinsci/plugins/p4/workspace/StreamWorkspaceImpl.java
JENKINS-73585 : Fix issue for streamAtChange not working
=> JENKINS-73585 : Fix issue for streamAtChange not working

src/main/java/org/jenkinsci/plugins/p4/publish/P4PublishEnvironmentContributingAction.java, src/main/java/org/jenkinsci/plugins/p4/publish/PublishNotifier.java, src/main/java/org/jenkinsci/plugins/p4/publish/PublishNotifierStep.java, src/main/java/org/jenkinsci/plugins/p4/tasks/PublishTask.java
=> Changelist Id of publish task should be available as environment variable

pom.xml
=> Update minimum supported jenkins version to 2.462.3

pom.xml, src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- For workspaces created with a virtual stream that is a child of a sparse stream, the Jenkinsfile path should include the path of the sparse stream.
=> - Update P4Java Version

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/build/P4StreamEnvironmentContributionAction.java
=> Expose streamAtChange to environment variable P4_STREAM_AT_CHANGE

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java, src/main/java/org/jenkinsci/plugins/p4/review/ReviewAction.java, src/main/java/org/jenkinsci/plugins/p4/review/ReviewNotifier.java, src/main/java/org/jenkinsci/plugins/p4/review/ReviewProp.java, src/main/java/org/jenkinsci/plugins/p4/workflow/P4SwarmUpdateStep.java, src/main/java/org/jenkinsci/plugins/p4/workflow/source/P4SwarmUpdateAction.java, src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/global.jelly, src/main/resources/org/jenkinsci/plugins/p4/workflow/P4SwarmUpdateStep/config.jelly, src/main/webapp/help-update.html
- Added support to update callback from swarm tests.
- Added new step p4SwarmUpdate, client can use this step in the pipeline to send custom message to update callback.
=> Add Support to Swarm Update URL.

src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java, src/main/java/org/jenkinsci/plugins/p4/build/P4StreamEnvironmentContributionAction.java, src/test/java/org/jenkinsci/plugins/p4/client/StreamAtChangeTest.java
=> Add stream name to P4_STREAM environment variable.

src/main/java/org/jenkinsci/plugins/p4/scm/BranchesScmSource.java, src/main/resources/org/jenkinsci/plugins/p4/scm/BranchesScmSource/config-detail.jelly
This can be enabled by checkbox in advance configuration 'Use new directory structure'
=> feat: For SwarmScmSource support new directory structure.

src/main/java/org/jenkinsci/plugins/p4/review/ReviewNotifier.java
Report Swarm URL PASS FAIL errors in the console log as informational but do not fail job
=> Given support for console logs for url pass / fail / update

src/main/java/org/jenkinsci/plugins/p4/scm/SwarmScmSource.java, src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
Added a check to compare the swarm project and respective branch with the user given project and branch.
=> Adding check for swarm project and branch
