- src/main/java/org/jenkinsci/plugins/p4/workspace/TemplateWorkspaceImpl.java
This fixes the issue for me both in instances of creating a new workspace from a template, and in updating a previously-created workspace from a template.
> Fix JENKINS-28760: Set line endings explicitly for template workspaces

- src/main/java/org/jenkinsci/plugins/p4/tasks/CheckoutTask.java
Adding an isEmpty() check after expanding the value of the
populateLabel, since a parameter value may be empty.
> JENKINS-29943: Check for empty param values

- src/main/java/org/jenkinsci/plugins/p4/credentials/TicketModeImpl.java
Using StringUtils.isEmpty() rather than null check to see if ticketValue
/ ticketPath are set since both values are explicitly marked non null.
Previously, ticketValue was empty, but isTicketValueSet() returned true
when the user intended to use a ticket file instead.
> [FIXED JENKINS-30163] P4TICKETS file credential doesn't work

- src/main/java/org/jenkinsci/plugins/p4/review/ReviewAction.java
- src/main/java/org/jenkinsci/plugins/p4/review/SafeParametersAction.java
- src/test/java/org/jenkinsci/plugins/p4/client/ConnectionTest.java
This PR fixes parameters visibility after SECURITY-170 inclusion in core (1.651.2 or 2.3+).
It also fixes tests failing under `mvn test -Djenkins.version=1.651.2` (due to the same issue).
@reviewbybees
> [JENKINS-35210] Fix for SECURITY-170

- src/main/java/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilder.java
- src/main/resources/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilder/config.jelly
- src/main/resources/org/jenkinsci/plugins/p4/workflow/P4UnshelveStep/config.jelly
switch dropdown list for merge options from basic jelly select option to ListBoxModel Option configured in Descriptor, this fixes issue with dropdown list not being set with selected value after saving and then entering configuration again
> Convert merge options for unshelve to ListBoxModel Option (from basic jelly) 

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
We created a 'Freestyle project' (which restricted on remote node) and choose 'Perforce Software'  with 'Template (view generated for each node)', and then enable 'Poll SCM'. it'll set the workspace's 'Root' to 'null'.
Another thing when we used "p4sync" step with template mode to sync code in our Pipeline job and enabled "Poll SCM" in Pipeline job and at the same time.  When polling, it will overwrite the workspace's "Root" with "null" too. And from the debugging, it seems polling on 'master'.
<-pollWorkspace:306, PerforceScm (org.jenkinsci.plugins.p4), PerforceScm.java
<- compareRemoteRevisionWith(Job, Launcher, FilePath, TaskListener, SCMRevisionState):281, PerforceScm (org.jenkinsci.plugins.p4), PerforceScm.java
<-poll(TaskListener):603, WorkflowJob …
> Workspace's root path overwritten to "null" when enabling polling in Pipeline job

- src/main/java/org/jenkinsci/plugins/p4/email/P4AddressResolver.java
Partially related to https://issues.jenkins-ci.org/browse/JENKINS-28421
The P4AddressResolver was not ending up in the list of resolvers in the mailer-plugin.
> Make P4AddressResolver discoverable

- src/main/java/org/jenkinsci/plugins/p4/client/Validate.java
- src/main/java/org/jenkinsci/plugins/p4/console/P4ConsoleAnnotator.java
We found that the post validation process didn't throw exception when some unknown errors (except for those ignoring ones ) occurred during P4 task.
> Not throw AbortException when unknown errors (except for those ignoring ones ) occurred during P4 task post-validation

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
This fixes the case where multiple checkouts are present
in a pipeline for example and they are nested. Then using
the latest change instead of the first (as done previously)
ensures that continous builds are not triggered. This
does not fix the case where the checkouts are completely
disjoint.
JENKINS-40048
> Use latest change for all builds when polling

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
Fixes [JENKINS-41459](https://issues.jenkins-ci.org/browse/JENKINS-41459)
Avoids this NPE triggered by Blue Ocean trying to get the URL for the repository browser. Bad for Blue Ocean as it causes the page not to render. 
PTAL @p4paul :)
```
java.io.IOException: Failed to write changeSet
at io.jenkins.blueocean.commons.stapler.export.Property.safeGetValue(Property.java:152)
at io.jenkins.blueocean.commons.stapler.export.Property.writeTo(Property.java:127)
at io.jenkins.blueocean.commons.stapler.export.Model.writeNestedObjectTo(Model.java:228)
at io.jenkins.blueocean.commons.stapler.export.Model.writeNestedObjectTo(Model.java:224)
at io.jenkins.blueocean.commons.stapler.export.Model.writeNestedObjectTo(Model.java:224)
at io.jenkins.blueocean.commons.stapler.export.Property.writeValue(Propert …
```
> JENKINS-41459 fixes NPE when credential is null

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- src/main/java/org/jenkinsci/plugins/p4/populate/FlushOnlyImpl.java
- src/main/resources/org/jenkinsci/plugins/p4/populate/FlushOnlyImpl/config.jelly
- src/main/resources/org/jenkinsci/plugins/p4/populate/FlushOnlyImpl/help-pin.html
This sync uses the `-k` flag in perforce to be able to use an already
existing sync on disk with a newly created clientspec.
> Implement a FlushOnly sync for "Populate Options"

- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeEntry.java
- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
P4Java has not limit support for getChangelistFiles; this is a
temporary workaround using execMap and the -m flag.
> Limit output from describe.

- .gitignore
- pom.xml
- src/main/java/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilder.java
- src/main/java/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilderStep.java
- src/main/java/org/jenkinsci/plugins/p4/workflow/P4UnshelveStep.java
- src/main/resources/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilder/config.jelly
**What:**
Added a checkbox to unshelve build step to skip itself if changelist ID was not entered.
Basically it just returns true in this case and build can continue.
**Why:**
Our build pipeline is quite complex, and the templates and parametric builds are used everywhere.
Currently the build would fail if the changelist ID is not set, as the plugin would actually try to parse null value. 
Since our tasks are instances of a master template that meant this value has to always be set, so we had to maintain couple of different templates if we wanted changelist unshelve option included.
With this we can have single template with option define in child task that implements it.
> P4Unshelve build step can now be skipped successfully if the changelist ID is not set

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
JENKINS-47141 - Fixes a NullPointerException when trying to unshelve (print) deletes of exclusively locked files
> Manually delete exclusively locked files for reviews

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
- src/main/java/org/jenkinsci/plugins/p4/tagging/TagAction.java
This fixes https://issues.jenkins-ci.org/browse/JENKINS-34052 and removes the need for https://issues.jenkins-ci.org/browse/JENKINS-41849. There is discussion in JENKINS-41849 about this being optional (as its definitely breaking backwards compatibility). Definitely up to the maintainer whether or not this should be optional or the new default.
> [FIX JENKINS-34052] Poll for concurrent jobs

- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java
This is my proposed fix for [JENKINS-48845](https://issues.jenkins-ci.org/browse/JENKINS-48845).
Basically, if the getSwarm() throws a RequestException for which the message contains "Unknown command", we deduce the P4 version doesn't support the Swarm stuff yet, and we let it slide.
I applied this fix to the 1.8.4 release, compiled and installed it on our production Jenkins, and it works.
> JENKINS-48845 : Backward compatibility for pre-swarm P4 releases

- .gitignore
- src/main/java/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/PollTask.java
- src/main/resources/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl/config.jelly
- src/main/resources/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl/help-patternList.html
- src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
The ViewMask filter leaves a LOT to be desired, especially if you want a lot of control on SCM polling such as on certain filetypes. This filter should give a large amount of control via Java regular expressions (patterns).
The only thing I couldn't figure out how to do was implement Console logging when I detected an improper Pattern from my filter class (ideally we could even catch this in the test and ensure the logging is there). Would love to hear any advice on how to accomplish that.
> Implementing a Java Pattern filter for polling

- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
With multibranch pipelines, when one of the branches contains a deleted Jenkinsfile, a project is created anyway for this branch, and the build fails.
With this fix, we're making sure that the Jenkinsfile is available before creating the branch. Tested on Jenkins.
I had trouble adding automated tests for this: I found tests where a file is submitted, but I can't seem to figure out how I can simulate a file deletion.
> Make sure branch is not discovered when a Jenkinsfile has been removed.

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
Added check for "can't move/delete" in addition to the existing "can't delete" check.
> Fix issue unshelving move/delete of locked files

- src/main/java/org/jenkinsci/plugins/p4/trigger/P4Hook.java
- src/main/java/org/jenkinsci/plugins/p4/trigger/P4HookCrumbExclusion.java
Triggering p4 scans should not require an account nor convoluted scripting. Add a CrumbExclusion on `/p4/change`, like Github and BitBucket have done:
https://github.com/jenkinsci/github-plugin/commit/5c2a04169171cb8e36da7ba39c4003aa318c74cb
https://github.com/jenkinsci/bitbucket-plugin/compare/924bdd21c704...67fb8b71eea7
> Add CrumbExclusion for /p4/change

- src/main/java/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor.java
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
[JENKINS-53221] Add P4_ROOT to environment variables. Extracting the workspace root information from the tag action. https://issues.jenkins-ci.org/browse/JENKINS-53221
> [JENKINS-53221] Add P4_ROOT to environment variables

- src/main/java/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4AffectedFile.java
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
Only a subset of FileAction types were expanded in P4AffectedFile. Adding the full set. https://issues.jenkins-ci.org/browse/JENKINS-53222
> [JENKINS-53222] Add all FileAction enum types to P4AffectedFile

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
- src/main/java/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor.java
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
Remove the gates on polling for if a job is building and if concurrent builds are enabled. This will allow polling to always occur and allow builds to queue up, preventing an unnecessary quiet period in between builds when changes are available. https://issues.jenkins-ci.org/browse/JENKINS-53224
> [JENKINS-53224] Disable polling bypass

- src/main/java/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor.java
There seems to be no reason to call TagAction.getTicket() in P4EnvironmentContributor if tickets are set to be hidden. So let's not, since it's a potentially expensive operation (less so since 83baa531 but still).
> Avoid unnecessary call to TagAction.getTicket()

- src/main/resources/org/jenkinsci/plugins/p4/credentials/P4TicketImpl/credentials.jelly
This change tells the Web UI to treat the P4Ticket field as a password, instead of treating it as plain text.
> Changed P4Ticket web field type to password

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
See [JENKINS-58504](https://issues.jenkins-ci.org/browse/JENKINS-58504)
Some use cases where the issue occurs include:
1) Using PerforceSCM to checkout a Jenkinsfile, followed by additional PerforceSCM checkouts
2) Using another SCM to checkout a Jenkinsfile, followed by additional PerforceSCM checkouts
In either case, each of the additional PerforceSCM checkouts will retrieve the Jenkinsfile/Pipeline script path from the `CpsScmFlowDefinition` and run `p4 where <scriptPath>`. Since the clients for these additional checkouts don't include the Jenkinsfile, the `p4 where` command returns `file(s) not in client view.`
> [JENKINS-58504] Only set the script path for pipeline script checkout

- src/main/java/org/jenkinsci/plugins/p4/tasks/CheckoutTask.java
There is no point in querying the server when syncing at CL 0 since that CL cannot exist.  So this is both an optimization and preventing a problematic query.
> JENKINS-58686 - Don't query submitted changes when syncing to CL 0.

- src/main/java/org/jenkinsci/plugins/p4/credentials/P4InvalidCredentialException.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4Task.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/P4Groovy.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/P4GroovyTask.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/AbstractTask.java
- src/test/java/org/jenkinsci/plugins/p4/groovy/P4GroovyTest.java
Use Run to determine the credentials in GetP4Task, then pass the
P4BaseCredentials instead of the credentials ID.
Now the P4Groovy getConnection() method uses the P4BaseCredentials
instead of looking up the credentials from the active Jenkins instance.
> Credentials handling for Folders when using P4Groovy

- src/main/java/org/jenkinsci/plugins/p4/credentials/P4InvalidCredentialException.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/GetP4Task.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/P4Groovy.java
- src/main/java/org/jenkinsci/plugins/p4/groovy/P4GroovyTask.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/AbstractTask.java
- src/test/java/org/jenkinsci/plugins/p4/groovy/P4GroovyTest.java
Use run to determine the credentials in GetP4Task, then pass the P4BaseCredentials instead of the credentials ID.  
Now the P4Groovy getConnection() method uses the P4BaseCredentials instead of looking up the credentials from the active Jenkins instance.
JENKINS-58745 JENKINS-57314
> Credentials handling for Folders when using P4Groovy.

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
https://issues.jenkins-ci.org/browse/JENKINS-52806 - Store the tagAction created by this perforce scm and use it for creating environment variables.  This prevents this perforce scm from setting the environment variables based on another perforce scm's tag action.
> Fix for p4 environment variables being wrong in parallel pipeline syncs

- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
- src/main/resources/org/jenkinsci/plugins/p4/scm/StreamsScmSource/help-includes.html
Fix for https://issues.jenkins-ci.org/browse/JENKINS-56290
> [JENKINS-56290] Impossible to Add Streams with Exact Names to Multibranch Pipeline

- src/main/java/org/jenkinsci/plugins/p4/client/ViewMapHelper.java
- src/test/java/org/jenkinsci/plugins/p4/client/ViewMapHelperTest.java
I'm epxeriencing an error where the viewmap helper fails to parse a multi-path depotSource, trying to reproduce in test.
First step was to get the tests running for a simple example.
To reproduce in the wild do something like this:
```
p4sync(
charset: 'utf8',
credential: 'CREDENTIALS',
format: "this-is-my-workspace",
populate: autoClean(
delete: true,
modtime: false,
parallel: [enable: false, minbytes: '1024', minfiles: '1', threads: '4'],
pin: '',
quiet: true,
replace: true,
tidy: false
),
source: depotSource("""
//depot/foo/...
//depot/bar/...
""")
)
```
Notice the leading and trailing newlines, producing empty lines for the viewmapper.
> Allow spacing around viewmappings

- src/main/java/org/jenkinsci/plugins/p4/trigger/P4Hook.java
When the endpoint /change is triggered it immediately generates and stores a list of Jenkins jobs then queues a task in the executorService.  This can lead to problems in big installations where there are lots of jobs that rely on p4 triggers and the Perforce instance is very active.
Say for instance it takes 2mins for a task to run through a list of jobs and poke each one.  Then you get 10 trigger requests in rapid succession.  It'll take 18mins to get to the last task instance.  During this time it's possible for jobs to be added / removed that rely on the trigger mechanism.  If a job is added just after the 10 trigger requests were sent then in this example it'll take approx 18mins before that job is poked by the trigger mechanism.
In our worst case we saw a 2hr delay before new jobs …
> Get list of jobs immediately prior to probing

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
Maven jobs, as well as some other plugins, update job config (config.xml) during the build. This is also the case when a job has been generated from DSL. After P4 checkout is complete, "tagAction" in PerforceScm is not null, and when a job is saved again it ends up being written to config.xml.
Steps to reproduce:
1. Create Maven job from DSL, using Perforce repository.
2. Start job, wait until P4 checkout is complete.
3. Check config.xml for the job; it will be reformatted from initial DSL representation, and will also have "tagAction" attribute under "scm" section.
This also causes NPE errors during Perforce checkout, under certain conditions, although these are much harder to reproduce. In any case, tagAction should be written to "Run" XMLs only, not build job configuration itself.
> tagAction should not be written to config.xml

- src/main/java/org/jenkinsci/plugins/p4/tasks/AbstractTask.java
We are getting an abort exception with the message: "Unmarshalable value in RpcStreamConnection.marshal; type: java.lang.Long"  In order to debug this issue I want to see where its being thrown in the p4 plugin.  But the AbortException passed back doesn't contain its cause - so the original exception is lost.  I'd like to pass back the cause so advanced developers like us can more easily get the backtrace when its needed.  Shouldn't affect normal users since AbortException doesn't print a backtrace by default.
> Initialize the cause of AbortException

- src/main/resources/org/jenkinsci/plugins/p4/changes/P4ChangeSet/digest.jelly
- src/main/resources/org/jenkinsci/plugins/p4/changes/P4ChangeSet/index.jelly
This should help support themes.
The drawback is now there's no visual differentiation between shelved/committed, but personally I don't see much value in that, and I wasn't sure how to do that without breaking IE compatibility.
I figured I'd log a PR to gauge interest.
The icons also need updating with transparency, but that can be a separate issue.
> Remove background colour for change list

- pom.xml
Load documentation from Github instead of the wiki.
Related tickets:
https://issues.jenkins-ci.org/browse/WEBSITE-406
https://issues.jenkins-ci.org/browse/JENKINS-59172
More info:  https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/
> Use Github as source of documentation

- src/main/java/org/jenkinsci/plugins/p4/scm/SwarmScmSource.java
When SwarmSCMSource#getHeads() calls swarm for the branches incorrectly sets the swarm branch id instead of the branch name on P4SCMHead object. This causes the env. variable BRANCH_NAME to have an incorrect value since the swarm id is always lower-case from the API.
For example, calling Swarm API `http://swarm/api/v4/projects/my-application?fields=branches` returns 
`{
"project": {
"branches": [
{
"id": "dev-security-fixes",
"name": "dev-Security-fixes",
"workflow": null,
"paths": [
"//Depot/my-application/dev-Security-fixes/..."
],
"minimumUpVotes": null,
"retainDefaultReviewers": false,
"moderators": []
}
]
}
}`
In the API response we see `"id": "dev-security-fixes"` and `"name": "dev-Security-fixes"`. Ideally the BRANCH_NAME should contain 'dev-Security-fixes' and not the lower-case …
> SwarmSCMSource#getHeads uses swarm id instead of name for P4SCMHead

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- src/main/java/org/jenkinsci/plugins/p4/scm/P4ChangeRequestSCMHead.java
- src/main/java/org/jenkinsci/plugins/p4/scm/SwarmScmSource.java
- src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmHelper.java
- src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmReviewAPI.java
- src/main/java/org/jenkinsci/plugins/p4/swarmAPI/SwarmReviewsAPI.java
- src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
This change adds the author property to the query string of the /review Swarm API call and then adds the author information to P4ChangeRequestSCMHead. This allows the jenkins.branch.BranchNameContributor to add env variable CHANGE_AUTHOR to the build environment properties.
> Add ContributorMetadataAction to SwarmScmSource to enable CHANGE_AUTHOR env variable in build

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
Existing code for populating workspace at  a "Pinned" change or label supports using a counter name,  see src/main/java/org/jenkinsci/plugins/p4/tasks/CheckoutTask.java line 95.   However the Polling code assumes the passed in "changeLimit" can be directly used in a "p4 changes @change1,@changeLimit" type of command, and this fails when a counter name is used.   The proposed change will check if the changeLimit is a counter, and if so substitute the counter value for the "changeLimit".   
Included new unit test for polling with a counter as the pinned change.
Without the fix, SCM polling with a pinned value of a counter named "my_counter_name" would result in 
P4: Task Exception: com.perforce.p4java.exception.RequestException: Invalid changelist/client/label/date '@my_counter_name'.
No …
> allow polling scm when populate options in job are set to pin to counter name in addition to changelist or label

- src/main/java/org/jenkinsci/plugins/p4/filters/FilterPatternListImpl.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/PollTask.java
Filters are specified as multi-line strings, but only support Unix
linebreaks (\n). This extends them to also support other platforms'
linebreaks, using the Java8 \R regex matcher for "any Unicode linebreak
sequence".
This is particularly useful if you have your Jenkins controller on a
Windows machine and you're specifying view filters as multiline groovy
strings. E.g.
```groovy
filter: [viewFilter('''//depot/path1
//depot/path2''')]
```
In this case, only the last path listed would be considered correctly,
because it would match the paths using
`p.startswith("//depot/path1\r")`, which would never be true.
> Add support for Windows linebreaks in filters

- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/filters/FilterPerChangeImpl/help-perChange.html
- src/test/java/org/jenkinsci/plugins/p4/client/PollingTest.java
It has effect only when "Polling per change" filter is active.
When P4_INCREMENTAL environment variable exists and has string value "false",
"Polling per change" filter is ignored and all pending changelists are built.
If this parameter does not exist or has value "true", "Polling per
change" filter works normally.
This is to allow controlling of "Polling per change" behavior in
FreeStyleProject jobs.
It is implementation of JENKINS-66169.
> Add support for controlling polling per change filter behavior with build parameter

- src/main/java/org/jenkinsci/plugins/p4/tasks/CheckoutTask.java
When initializing a `CheckoutTask` with a `P4LabelRef=now`, replace it with a `P4ChangeRef=head`.
See: https://issues.jenkins.io/browse/JENKINS-66648.
> [JENKINS-66648] Replace 'now' label with the P4ChangeRef for the current head

- src/main/resources/org/jenkinsci/plugins/p4/review/ReviewAction/index.jelly
- src/main/resources/org/jenkinsci/plugins/p4/trigger/P4Hook/index.jelly
Preparation for core removing sunset icons: `https://github.com/jenkinsci/jenkins/pull/5778/`
@p4paul Would be nice if you can also trigger a release after merging this PR.
Thanks in advance!
> chore: Prepare for sunset icon removal from core

- src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java
- src/test/java/org/jenkinsci/plugins/p4/DefaultEnvironment.java
- src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
execution
WHAT
1. If multibranch project trigger a build for a branch then it should
build for head which is in the Observer and not for all heads that
matches the multibranch.
> JENKINS-64946 : Branch indexing occurring for every multibranch job

- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeEntry.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeSet.java
This allows a script to interrogate `isFileLimit()` reliably when a
changeset is serialized and then deserialized.
Without this change,
`src\main\resources\org\jenkinsci\plugins\p4\changes\P4ChangeSet\index.jelly`
does not correctly display the `...list truncated` string that it intends to.
> Persist `fileLimit` when serializing a changeset

- RELEASE.md
- docs/P4GROOVY.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/p4/ConfigurationListener.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeEntry.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeSet.java
- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
- src/main/java/org/jenkinsci/plugins/p4/client/NavigateHelper.java
- src/main/java/org/jenkinsci/plugins/p4/client/SessionEntry.java
- src/main/java/org/jenkinsci/plugins/p4/client/SessionHelper.java
- src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java
- src/main/java/org/jenkinsci/plugins/p4/tagging/TagAction.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/TaggingTask.java
- src/main/resources/org/jenkinsci/plugins/p4/review/ReviewAction/index.jelly
- src/main/resources/org/jenkinsci/plugins/p4/trigger/P4Hook/index.jelly
- src/test/java/org/jenkinsci/plugins/p4/DefaultEnvironment.java
- src/test/java/org/jenkinsci/plugins/p4/scm/P4SCMFileSystemTest.java
- src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
The bug is in the p4tag pipeline function.
The object creates the new label mapping based on the string of the client mapping, but the exclude marker "-" is not part of the string.  The type needs to be restored before adding the entry to the label view mapping.  One line change to call setTag on the new entry.
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
> Fix bug where exclude paths are turned into include paths

- RELEASE.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/p4/ConfigurationListener.java
- src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeEntry.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeParser.java
- src/main/java/org/jenkinsci/plugins/p4/changes/P4ChangeSet.java
- src/main/java/org/jenkinsci/plugins/p4/client/SessionHelper.java
- src/main/java/org/jenkinsci/plugins/p4/scm/AbstractP4ScmSource.java
- src/main/java/org/jenkinsci/plugins/p4/tasks/TaggingTask.java
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.groovy
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
- src/test/java/org/jenkinsci/plugins/p4/DefaultEnvironment.java
- src/test/java/org/jenkinsci/plugins/p4/client/FreeStyleTest.java
- src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
When using SyncOnlyImpl, setting P4_CLEANWORKSPACE variable can
be used to request wiping workspace and doing fresh sync when
needed. When P4_CLEANWORKSPACE is set and "true", build workspace
is cleaned and then force sync and update have list is requested.
This implements https://issues.jenkins.io/browse/JENKINS-66603
> Force sync and populate have list on P4_CLEANWORKSPACE

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
Setting the global option maxChanges (Maximum number of changes shown in a 
build) to 0 will skip collecting the changes for a build, no longer running the
"p4 changes ...@ last,current".  As a global option, this affects all builds.
> Allow option to not detect changelists for build, JENKINS-68516

- src/main/java/org/jenkinsci/plugins/p4/publish/PublishNotifier.java
- src/main/java/org/jenkinsci/plugins/p4/publish/PublishNotifierStep.java
Ensure the perforce client is cleaned up after publishing when the cleanup attribute is set on the workspace.
This is to address https://issues.jenkins.io/browse/JENKINS-69808
Note: I'm not very familiar with the Jenkins code base, so a thorough review would be appreciated.
> JENKINS-69808: Cleanup client after publish, if enabled

- src/main/java/org/jenkinsci/plugins/p4/workspace/ManualWorkspaceImpl.java
- src/test/java/org/jenkinsci/plugins/p4/client/WorkspaceSpecTest.java
When retrieving a view spec from a file (@//depot/path/to/view.txt) or a ManualWorkspace View, rows may only contain a depot view (LHS). The client RHS will be created if missing.
If LHS is "//depot/path/to/project/..." we'll add the RHS of "//CLIENT/path/to/project/..." using the correct client name.
JENKINS-69491
Also code cleanup:  convert spaces to tabs, adjust import ordering.
> For ManualWorkspace views from a file, construct RHS if missing.

- src/main/java/org/jenkinsci/plugins/p4/tasks/UnshelveTask.java
- src/main/java/org/jenkinsci/plugins/p4/unshelve/UnshelveBuilder.java
- src/test/java/org/jenkinsci/plugins/p4/scm/PerforceSCMSourceTest.java
Unable to unshelve change: java.lang.IllegalStateException: Expected 1 instance of hudson.model.User$AllUsers but got 0
https://issues.jenkins.io/browse/JENKINS-69172
When unshelve task is executed on a slave node, then Jenkins.getInstance() can not be used, hence no user is found while updating the changelog.
The changelog will get updated once the build is successful.
> Fix for:  Unable to unshelve change: java.lang.IllegalStateException: Expected 1 instance of hudson.model.User$AllUsers but got 0

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
This is the fix for bug: https://issues.jenkins.io/browse/JENKINS-59922 This flag was suppoerted by p4d after 2019.1 release(#1726148 (Job #51996) ), so set it in p4jenkins for this or later versions
> Add '-t' flag to reconcile command.

- src/main/java/org/jenkinsci/plugins/p4/client/ConnectionHelper.java
- src/test/java/org/jenkinsci/plugins/p4/SimpleTestServer.java
- src/test/java/org/jenkinsci/plugins/p4/client/ConnectionTest.java
do not call "p4 counter <value>" when the value is an integer as the helix core server does not allow integer counters.
in isCounter() method, check for all digits early.  If all digits, return false. 
Fix for JENKINS-70219: server's errors.csv fills up when populate's "pin" is to changelist.
Added simple isCounter() test to check:
1)  a counter that exists
2)  a counter that does not exit
3)  that a numeric counter doesn't call p4d (JENKINS-70219)
> When checking if a value is a counter, do not call "p4 counter" for integer values

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
After the Pipeline Groovy Library was modified to delete the temporary directory itself
(https://github.com/jenkinsci/pipeline-groovy-lib-plugin/commit/76ad53e052aa7b9a7d0101b23e83a8ed5ab43feb)
global libraries failed with Perforce modern SCM
[JENKINS-72098](https://issues.jenkins.io/browse/JENKINS-72098)
[JENKINS-71763](https://issues.jenkins.io/browse/JENKINS-71763)
The issue arises because '**FileUtils.forceDelete**' throws a '**java.io.IOException: DOS or POSIX file operations not available for**'
when the file does not exist on Windows, even though the documentation indicates it should throw a '**FileNotFoundException**'
https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FileUtils.html#forceDelete(java.io.File)
I have added a check for path existence after …
> JENKINS-72098: Cant sync global libraries on Windows

- src/main/java/org/jenkinsci/plugins/p4/workspace/ManualWorkspaceImpl.java
Also support "@" in the view for polling.
This is a continuation of what was implemented for JENKINS-69491, but the polling view was forgotten.
```[tasklist]
```
> [JENKINS-69491] Implement support for "@/path/to/spec" for "poll view" in ManualWorkspaceImpl.java too

- src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java
Original patch by Akos Bannerth
Closes: https://issues.jenkins.io/browse/JENKINS-72335
When using p4publish with multiple paths listed in the `paths` argument, and the workspace doesn't contain any changes compared to the depot, publish will fail with
```
Unable to publish workspace: hudson.AbortException: P4JAVA: Error(s):
No file(s) to reconcile.
```
This seems to be a result of a check in [ClientHelper.java](https://github.com/jenkinsci/p4-plugin/blob/master/src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java#L796)
```
getValidate().check(status, "- no file(s) to reconcile", "instead of", "empty, assuming text", "also opened by");
```
which apparently should ignore the p4java status "- no file(s) to reconcile" but when reconciling with multiple paths, the message is "No …
> client/ClientHelper.java: fix check for p4 error message when there are multiple files to reconcile

- src/main/java/org/jenkinsci/plugins/p4/client/Validate.java
Added a new overload for [Validate#checkCatch](https://github.com/jenkinsci/p4-plugin/blob/2922a8d230537f535b5d1fbf3c7334f18438fa7f/src/main/java/org/jenkinsci/plugins/p4/client/Validate.java#L43) that exposes the `quiet` flag to the user.
Implementation for [JENKINS-72884](https://issues.jenkins.io/browse/JENKINS-72884)
N/A
```[tasklist]
```
> Add Validate#checkCatch overload to set quiet flag

- src/main/resources/org/jenkinsci/plugins/p4/PerforceScm/buildEnv.properties
- src/main/resources/org/jenkinsci/plugins/p4/build/P4EnvironmentContributor/buildEnv.properties
https://issues.jenkins.io/browse/JENKINS-73075
JENKINS-73075 : P4_CHANGELIST is not documented when there are no changelists in workspace
Description Of changes -> I changed the documentation of **P4_CHANGELIST**  from `The last Perforce changelist number included in the populated workspace.` to `The last Perforce changelist number included in the populated workspace, or the latest changelist number across the Perforce server if no changelist is found in the workspace.` as discussed in the issue discussion. 
This documentation also helps the users with understanding the content of P4_CHANGELIST when a workspace is not populated.
> P4_CHANGELIST documentation Upgraded

- src/main/java/org/jenkinsci/plugins/p4/scm/GlobalLibraryScmSource.java
Helix Libraries loaded with Modern SCM should not create a new directory for each build.
Fix For: JENKINS-73323
> Modern SCM Helix Libraries directories never reused

- src/main/java/org/jenkinsci/plugins/p4/trigger/P4Hook.java
Let me know if this needs more work or any changes 😁
> Replace hardcoded value with StandardCharset
